
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    networks:
      - app_network
    expose:
      - 5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
